.export START_GAME_LOOP

.import READ_GAMEPAD_1, SET_BACKGROUND_COLOR, ENABLE_PPU_RENDERING
.import ENABLE_NMI_INTERRUPTS, SET_PALETTE, HELLO_WORLD
.importzp GAMEPAD_1, GAMEPAD_STATUS, A_STATUS, X_POS, Y_POS

.include "include/gamepad.inc"
.include "include/macros.inc"

.proc START_GAME_LOOP
    ;JSR SET_BACKGROUND_COLOR
    LDA #0
    STA X_POS
    STA Y_POS
    JSR SET_PALETTE
    JSR HELLO_WORLD
    
    JSR ENABLE_PPU_RENDERING
    JSR ENABLE_NMI_INTERRUPTS

  MAIN_LOOP:
    JSR READ_GAMEPAD_1
    ; store final result of game pad at memory location 1
    set GAMEPAD_STATUS, GAMEPAD_1
    ; check single button
    LDA GAMEPAD_1
    AND #GAMEPAD_UP_MASK
    BEQ NOT_PRESSED_U
    INC Y_POS
    NOT_PRESSED_U:
    LDA GAMEPAD_1
    AND #GAMEPAD_RIGHT_MASK
    BEQ NOT_PRESSED_R
    INC X_POS
  NOT_PRESSED_R:
    JMP MAIN_LOOP
.endproc